const currentRepository = 'siscomex-restituicao-front'

const searchPaths = [
  '/pages/**/*.vue',
  '/layouts/**/*.vue',
  '/app/**/components/**/*.vue'
]

const designSystemComponents = [
  'LAlert',
  'LAvatar',
  'LProgressBar',
  'LButtonNew',
  'LCard',
  'LCardHeader',
  'LCardNew',
  'LCardHeaderNew',
  'LBarChart',
  'LBarChartLine',
  'LCircularChart',
  'LGeneralChart',
  'LLinearChart',
  'LLinearChartLine',
  'LLinearChartExpand',
  'LLinearChartTotalValue',
  'LResumeChart',
  'LResumeLine',
  'LRouteChart',
  'LRouteChartHeader',
  'LRouteChartLine',
  'LLabeledChip',
  'LTextField',
  'LTextArea',
  'LCombobox',
  'LSelect',
  'LCheckboxNew',
  'LCheckbox',
  'LCheckboxList',
  'LDatePickerDay',
  'LDatePickerMonth',
  'LDropdownCheck',
  'LDropdownCheckbox',
  'LInputBorder',
  'LInputButton',
  'LInputLoaded',
  'LInputSolo',
  'LInputTag',
  'LLabeledInput',
  'LLabeledSelect',
  'LLabeledTextArea',
  'LSelectNamed',
  'LSelectSolo',
  'LLoading',
  'LModalNew',
  'LModalHeaderNew',
  'LModalFooterNew',
  'LModalContent',
  'LSimpleTable',
  'LTableNew',
  'LTag',
  'LTimeline',
  'LTimelineItem',
  'LTooltip'
]

module.exports = {
  currentRepository,
  searchPaths,
  designSystemComponents
}
